README.md
=> Remove duplicate link in README.md

README.md, mapbox-gl-js-react/.gitignore, mapbox-gl-js-react/README.md, mapbox-gl-js-react/package-lock.json, mapbox-gl-js-react/package.json, mapbox-gl-js-react/public/index.html, mapbox-gl-js-react/public/manifest.json, mapbox-gl-js-react/public/robots.txt, mapbox-gl-js-react/src/index.css, mapbox-gl-js-react/src/index.tsx, mapbox-gl-js-react/src/react-app-env.d.ts, mapbox-gl-js-react/tsconfig.json
Adds example using React with same structure as the Mapbox GL JS example.
=> Add Mapbox GL example with React

mapbox-gl-js-react/package-lock.json, mapbox-gl-js-react/package.json
=> Upgrade aws-amplify to pick up updated axios

mapbox-gl-js-react/package-lock.json, mapbox-gl-js-react/package.json
Move dependencies used for development into devDependencies.
=> Upgrade dependencies

tangram-es-android/app/build.gradle, tangram-es-android/app/src/main/res/values/configuration.xml, tangram-es-android/build.gradle
=> Update dependencies + attribution year

tangram-es-ios/Podfile.lock
=> Update dependencies for Tangram on iOS

mapbox-gl-js-react/README.md
Line number of `<MAP_NAME>` is 22 instead of 14.
=> Update line number of `<MAP_NAME>` in README.md

amazon-location-helpers/index.d.ts, amazon-location-helpers/webpack.config.js
=> Add missing license headers

README.md, geocode-udf-lambda-aurora/CloudFormation/geocode-lambda-aurora.yml, geocode-udf-lambda-aurora/Lambda/geocode.py, geocode-udf-lambda-aurora/Lambda/lambda_function.py, geocode-udf-lambda-aurora/README.md, geocode-udf-lambda-aurora/UDF/CreateFunction.sql, geocode-udf-lambda-redshift/CloudFormation/geocode-lambda-redshift.yml, geocode-udf-lambda-redshift/Lambda/geocode.py, geocode-udf-lambda-redshift/Lambda/lambda_function.py, geocode-udf-lambda-redshift/README.md, geocode-udf-lambda-redshift/UDF/CreateFunction.sql
=> Geocode UDF Lambda

geocode-udf-lambda-aurora/Lambda/geocode.py, geocode-udf-lambda-redshift/Lambda/geocode.py
=> Set User Agent strings to identify calls

geocode-udf-lambda-aurora/Lambda/geocode.py, geocode-udf-lambda-aurora/README.md, geocode-udf-lambda-aurora/UDF/CreateFunction.sql, geocode-udf-lambda-aurora/UDF/CreateTable.sql, geocode-udf-lambda-redshift/Lambda/geocode.py, geocode-udf-lambda-redshift/README.md, geocode-udf-lambda-redshift/UDF/CreateTable.sql
=> Updated UDF script, added create table scripts

geocode-udf-lambda-aurora/UDF/CreateTable.sql, geocode-udf-lambda-redshift/CloudFormation/geocode-lambda-redshift.yml, geocode-udf-lambda-redshift/UDF/CreateTable.sql
=> New fields added, parameter name fixed

amazon-location-helpers/README.md, amazon-location-helpers/index.d.ts, amazon-location-helpers/index.js, amazon-location-helpers/package-lock.json, amazon-location-helpers/package.json, amazon-location-helpers/webpack.config.js, maplibre-gl-js/index.html
=> Migrate to AWS SDK for JavaScript v3

maplibre-js-react-iot-asset-tracking/package-lock.json
=> Upgrade tar

create-custom-map-style/tileserver/package-lock.json, create-custom-map-style/tileserver/package.json
=> Upgrade tessera to eliminate outdated underscore dep

mapbox-gl-native-ios/README.md
=> Readme for mapbox native iOS

athena-udfs/pom.xml
=> Conform to Maven best practices for sample code

athena-udfs/amazon-location-udfs.yaml, athena-udfs/pom.xml
Corresponds to https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/create/app?applicationId=arn:aws:serverlessrepo:us-west-2:003883091127:applications/AmazonLocationUDFs
=> Update to latest AWS + Athena Federation SDKs + bump app version

README.md
=> Add Pizza Delivery Tracker sample

react-map-gl-amplify-change-map-language/src/hooks/useLocalizedStyleDescriptor.js
This PR fixes an issue with the style descriptor transformation for localised maps not being applied correctly with HERE maps.
---
=> fix: style-descriptor transformer in HERE

create-custom-map-style/package-lock.json, create-custom-map-style/package.json, create-custom-map-style/tileserver/package-lock.json, create-custom-map-style/tileserver/package.json, maplibre-gl-js-react-amplify/package-lock.json, maplibre-gl-js-react-amplify/package.json, maplibre-gl-js-react/package-lock.json, maplibre-gl-js-react/package.json, maplibre-js-react-iot-asset-tracking/generate_thing_events/package-lock.json, maplibre-js-react-iot-asset-tracking/generate_thing_events/package.json, maplibre-js-react-iot-asset-tracking/package-lock.json, maplibre-js-react-iot-asset-tracking/package.json, react-map-gl-amplify-change-map-language/package-lock.json, react-map-gl-amplify-change-map-language/package.json, react-map-gl-amplify-here-map/package-lock.json, react-map-gl-amplify-here-map/package.json, react-map-gl-amplify-marker-tooltip-example/package-lock.json, react-map-gl-amplify-marker-tooltip-example/package.json, react-map-gl-amplify/package-lock.json, react-map-gl-amplify/package.json, react-map-gl-clusters/package-lock.json, react-map-gl-clusters/package.json, react-map-gl-map-styles/package-lock.json, react-map-gl-map-styles/package.json, react-map-gl-markers/package-lock.json, react-map-gl-markers/package.json, react-map-gl-polygons/package-lock.json, react-map-gl-polygons/package.json
=> build(deps-dev): security fixes for minimist

amazon-location-helpers/package-lock.json, amazon-location-helpers/package.json, create-custom-map-style/package-lock.json, create-custom-map-style/package.json, leaflet-vue-amplify/package-lock.json, leaflet-vue-amplify/package.json, maplibre-gl-js-react-amplify/package-lock.json, maplibre-gl-js-react-amplify/package.json, maplibre-gl-js-react/package-lock.json, maplibre-gl-js-react/package.json, maplibre-gl-js-vue-amplify/package-lock.json, maplibre-gl-js-vue-amplify/package.json, maplibre-js-react-iot-asset-tracking/package-lock.json, maplibre-js-react-iot-asset-tracking/package.json, react-map-gl-amplify-change-map-language/package-lock.json, react-map-gl-amplify-change-map-language/package.json, react-map-gl-amplify-here-map/package-lock.json, react-map-gl-amplify-here-map/package.json, react-map-gl-amplify-marker-tooltip-example/package-lock.json, react-map-gl-amplify-marker-tooltip-example/package.json, react-map-gl-amplify/package-lock.json, react-map-gl-amplify/package.json, react-map-gl-clusters/package-lock.json, react-map-gl-clusters/package.json, react-map-gl-map-styles/package-lock.json, react-map-gl-map-styles/package.json, react-map-gl-markers/package-lock.json, react-map-gl-markers/package.json, react-map-gl-polygons/package-lock.json, react-map-gl-polygons/package.json
=> build(deps-dev): override aws-amplify/xcode/simple-plist

amplify-ui-geo-explore/.gitignore, amplify-ui-geo-explore/README.md, amplify-ui-geo-explore/vite.config.js
Added steps to support Amplify Hosting of the Explore App as well as updated instructions.
=> Updating Explore App for Amplify Hosting

README.md
=> Chore: remove broken link #185

maplibre-js-react-iot-asset-tracking/README.md
=> Issue 189 - Changes to README
